import os
import argparse
import hashlib
import json
import re
from datetime import datetime, timezone
from pathlib import Path

import requests
from markdownify import markdownify as md


def extract_rules(markdown_content: str) -> list[dict[str, str | None]]:
    rules: list[dict[str, str | None]] = []
    section = "General"

    for raw_line in markdown_content.splitlines():
        line = raw_line.strip()
        if not line:
            continue

        heading_match = re.match(r"^#{2,6}\s+(.+)$", line)
        if heading_match:
            section = heading_match.group(1).strip()
            continue

        bullet_match = re.match(r"^(?:\*|\-|\+)\s+(.+)$", line)
        if not bullet_match:
            continue

        text = bullet_match.group(1).strip()
        while re.match(r"^[+\-*]\s+", text):
            text = re.sub(r"^[+\-*]\s+", "", text).strip()
        # Skip placeholder bullets accidentally created by HTML conversion.
        if text in {"+", "-", "*"}:
            continue

        canonical = re.sub(r"\s+", " ", text)
        normalized = re.sub(r"[`*_]", "", canonical).lower()
        rule_hash = hashlib.sha1(f"{section}|{normalized}".encode("utf-8")).hexdigest()[:10]
        rule_id = f"DS-{rule_hash}"

        checker = None
        if "use snake_case for all identifiers" in normalized:
            checker = "sql_snake_case_identifiers"
        elif "format: [layer]_[domain]_[object]" in normalized:
            checker = "sql_table_layer_domain_object"
        elif "prefix fact tables with fact_" in normalized and "dimensions with dim_" in normalized:
            checker = "sql_fact_dim_prefix"
        elif "use utc timestamps exclusively" in normalized:
            checker = "utc_timestamp_usage"
        elif "retry logic" in normalized and "3 attempts" in normalized:
            checker = "retry_logic_presence"

        rules.append(
            {
                "id": rule_id,
                "section": section,
                "text": canonical,
                "checker": checker,
                "mitigation": default_mitigation(canonical),
            }
        )

    return rules


def default_mitigation(rule_text: str) -> str:
    lowered = rule_text.lower()
    if "snake_case" in lowered:
        return "Rename identifiers to snake_case and update all references in SQL, notebooks, and models."
    if "[layer]_[domain]_[object]" in lowered:
        return "Rename table/object to [layer]_[domain]_[object] and align references across pipelines and models."
    if "fact_" in lowered and "dim_" in lowered:
        return "Rename fact tables with fact_ and dimensions with dim_, then update dependent transformations."
    if "utc" in lowered:
        return "Replace local time usage with timezone-aware UTC timestamps and document conversion boundaries."
    if "retry" in lowered:
        return "Implement exponential backoff with exactly 3 retry attempts in pipeline/workflow logic."
    return "Align the PR changes with this rule and include evidence (tests, config, or documentation) in the PR description."


def render_validator_source(
    *,
    source_url: str,
    synced_at: str,
    page_title: str,
    rules: list[dict[str, str | None]],
) -> str:
    rules_literal = repr(rules)
    body = """\
\"\"\"Auto-generated validator from Confluence-backed development standards.

Do not edit manually. This file is generated by
.github/scripts/sync_development_standards.py.
\"\"\"

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass
class Violation:
    rule_id: str
    rule_text: str
    section: str
    file_path: str
    why: str
    mitigation: str


def list_changed_files(base_ref: str) -> list[Path]:
    merge_base = subprocess.check_output(
        ["git", "merge-base", base_ref, "HEAD"], text=True
    ).strip()
    out = subprocess.check_output(
        ["git", "diff", "--name-only", f"{merge_base}..HEAD"], text=True
    )
    return [Path(line.strip()) for line in out.splitlines() if line.strip()]


def read_text(file_path: Path) -> str:
    try:
        return file_path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return file_path.read_text(encoding="latin-1", errors="ignore")


def check_sql_snake_case_identifiers(file_path: Path, text: str) -> list[tuple[str, str]]:
    findings: list[tuple[str, str]] = []
    if file_path.suffix.lower() != ".sql":
        return findings

    for token in re.findall(r"\\b[A-Za-z][A-Za-z0-9_]*\\b", text):
        if token.lower() in {
            "select", "from", "where", "join", "group", "order", "by", "as", "and", "or", "on",
            "insert", "update", "delete", "create", "table", "view", "into", "values", "case",
            "when", "then", "else", "end"
        }:
            continue
        if token != token.lower():
            findings.append(
                (
                    f"Identifier '{token}' is not snake_case.",
                    "SQL identifiers must use snake_case.",
                )
            )
            if len(findings) >= 20:
                break
    return findings


def check_sql_table_layer_domain_object(file_path: Path, text: str) -> list[tuple[str, str]]:
    findings: list[tuple[str, str]] = []
    if file_path.suffix.lower() != ".sql":
        return findings

    pattern = re.compile(
        r'\\b(?:create|alter)\\s+table\\s+(?:if\\s+not\\s+exists\\s+)?([A-Za-z0-9_\\."\\[\\]]+)',
        re.IGNORECASE,
    )
    allowed = re.compile(r"^(bronze|silver|gold)_[a-z0-9]+_[a-z0-9_]+$")
    for match in pattern.finditer(text):
        raw = match.group(1)
        table_name = raw.split(".")[-1].strip('"[]').lower()
        if not allowed.match(table_name):
            findings.append(
                (
                    f"Table '{raw}' does not follow [layer]_[domain]_[object].",
                    "Expected layer prefix and domain/object naming standard.",
                )
            )
    return findings


def check_sql_fact_dim_prefix(file_path: Path, text: str) -> list[tuple[str, str]]:
    findings: list[tuple[str, str]] = []
    if file_path.suffix.lower() != ".sql":
        return findings

    pattern = re.compile(
        r'\\bcreate\\s+table\\s+(?:if\\s+not\\s+exists\\s+)?([A-Za-z0-9_\\."\\[\\]]+)',
        re.IGNORECASE,
    )
    for match in pattern.finditer(text):
        raw = match.group(1)
        table_name = raw.split(".")[-1].strip('"[]').lower()
        if "fact" in table_name and not table_name.startswith("fact_"):
            findings.append(
                (
                    f"Fact-like table '{raw}' is missing fact_ prefix.",
                    "Fact tables must be prefixed with fact_.",
                )
            )
        if "dim" in table_name and not table_name.startswith("dim_"):
            findings.append(
                (
                    f"Dimension-like table '{raw}' is missing dim_ prefix.",
                    "Dimension tables must be prefixed with dim_.",
                )
            )
    return findings


def check_utc_timestamp_usage(file_path: Path, text: str) -> list[tuple[str, str]]:
    findings: list[tuple[str, str]] = []
    suffix = file_path.suffix.lower()

    if suffix == ".py":
        if "datetime.now(" in text and "timezone.utc" not in text:
            findings.append(
                (
                    "datetime.now(...) detected without timezone.utc.",
                    "Use timezone-aware UTC timestamps in Python.",
                )
            )
    elif suffix == ".sql":
        local_time_tokens = ["GETDATE(", "CURRENT_TIMESTAMP", "SYSDATETIME("]
        for token in local_time_tokens:
            if token in text.upper():
                findings.append(
                    (
                        f"Potential local time function detected: {token}",
                        "Use UTC-compatible timestamp expressions.",
                    )
                )
    return findings


def check_retry_logic_presence(file_path: Path, text: str) -> list[tuple[str, str]]:
    findings: list[tuple[str, str]] = []
    if file_path.name.endswith((".yml", ".yaml")) and ".github/workflows/" in file_path.as_posix():
        lowered = text.lower()
        if "retry" not in lowered:
            findings.append(
                (
                    "Workflow does not mention retry handling.",
                    "Standards require 3 retry attempts with exponential backoff for scheduled refresh logic.",
                )
            )
    return findings


CHECKERS = {
    "sql_snake_case_identifiers": check_sql_snake_case_identifiers,
    "sql_table_layer_domain_object": check_sql_table_layer_domain_object,
    "sql_fact_dim_prefix": check_sql_fact_dim_prefix,
    "utc_timestamp_usage": check_utc_timestamp_usage,
    "retry_logic_presence": check_retry_logic_presence,
}


def validate(base_ref: str, include_manual: bool) -> tuple[list[Violation], list[dict]]:
    changed_files = [p for p in list_changed_files(base_ref) if p.exists()]
    violations: list[Violation] = []
    manual_rules: list[dict] = []

    text_cache: dict[Path, str] = {}
    for file_path in changed_files:
        if file_path.is_file():
            text_cache[file_path] = read_text(file_path)

    for rule in RULES:
        checker_name = rule.get("checker")
        if not checker_name:
            if include_manual:
                manual_rules.append(rule)
            continue

        checker = CHECKERS.get(checker_name)
        if checker is None:
            continue

        for file_path, text in text_cache.items():
            for why, evidence in checker(file_path, text):
                violations.append(
                    Violation(
                        rule_id=str(rule["id"]),
                        rule_text=str(rule["text"]),
                        section=str(rule["section"]),
                        file_path=file_path.as_posix(),
                        why=f"{why} {evidence}",
                        mitigation=str(rule["mitigation"]),
                    )
                )

    return violations, manual_rules


def to_markdown(
    violations: list[Violation],
    manual_rules: list[dict],
    source_url: str,
    last_synced_utc: str,
    page_title: str,
) -> str:
    lines = [
        "# Development Standards Validation Report",
        "",
        f"- Source: {source_url}",
        f"- Last synced: {last_synced_utc}",
        f"- Rules catalog title: {page_title}",
        "",
    ]

    if violations:
        lines.extend(["## Violations", ""])
        for item in violations:
            lines.extend(
                [
                    f"### {item.rule_id}",
                    f"- Section: {item.section}",
                    f"- File: {item.file_path}",
                    f"- Rule failed: {item.rule_text}",
                    f"- Why: {item.why}",
                    f"- Mitigation: {item.mitigation}",
                    "",
                ]
            )
    else:
        lines.extend(["## Violations", "", "No automated violations found.", ""])

    lines.extend(["## Manual Review Rules", ""])
    if manual_rules:
        for rule in manual_rules:
            lines.extend(
                [
                    f"### {rule['id']}",
                    f"- Section: {rule['section']}",
                    f"- Rule: {rule['text']}",
                    "- Why manual: No deterministic checker is mapped yet.",
                    f"- Mitigation: {rule['mitigation']}",
                    "",
                ]
            )
    else:
        lines.append("No manual rules recorded.")

    return "\\n".join(lines).strip() + "\\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate PR changes against development standards")
    parser.add_argument("--base-ref", default="origin/main", help="Base ref for PR diff (default: origin/main)")
    parser.add_argument(
        "--report-path",
        default="development-standards-validation.md",
        help="Where to write Markdown validation output",
    )
    parser.add_argument(
        "--include-manual",
        action="store_true",
        help="Include manual-review rule list in the report",
    )
    parser.add_argument(
        "--json-path",
        default="development-standards-validation.json",
        help="Where to write machine-readable violations",
    )
    args = parser.parse_args()

    violations, manual_rules = validate(args.base_ref, include_manual=args.include_manual)

    markdown_report = to_markdown(
        violations,
        manual_rules,
        source_url=SOURCE_URL,
        last_synced_utc=LAST_SYNCED_UTC,
        page_title=PAGE_TITLE,
    )
    Path(args.report_path).write_text(markdown_report, encoding="utf-8")

    json_payload = {
        "source": SOURCE_URL,
        "last_synced_utc": LAST_SYNCED_UTC,
        "rule_count": len(RULES),
        "violation_count": len(violations),
        "violations": [v.__dict__ for v in violations],
    }
    Path(args.json_path).write_text(json.dumps(json_payload, indent=2), encoding="utf-8")

    if violations:
        print(f"Validation failed: {len(violations)} violation(s).")
        print(f"Markdown report: {args.report_path}")
        print(f"JSON report: {args.json_path}")
        return 1

    print("Validation passed: no automated violations.")
    print(f"Markdown report: {args.report_path}")
    print(f"JSON report: {args.json_path}")
    return 0
"""

    return "\n".join(
        [
            body,
            f"SOURCE_URL = {source_url!r}",
            f"LAST_SYNCED_UTC = {synced_at!r}",
            f"PAGE_TITLE = {page_title!r}",
            "",
            f"RULES = {rules_literal}",
            "",
            'if __name__ == "__main__":',
            "    sys.exit(main())",
            "",
        ]
    )


def write_validator_file(*, source_url: str, synced_at: str, page_title: str, markdown_content: str) -> Path:
    rules = extract_rules(markdown_content)
    validator_source = render_validator_source(
        source_url=source_url,
        synced_at=synced_at,
        page_title=page_title,
        rules=rules,
    )

    output_file = Path("scripts/validate_development_standards.py")
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(validator_source, encoding="utf-8")
    return output_file


def require_env(name: str) -> str:
    value = os.environ.get(name, "")
    if not value:
        raise RuntimeError(f"{name} is empty or not set")
    return value


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Sync development standards from Confluence and generate validator"
    )
    parser.add_argument(
        "--from-instructions-file",
        default="",
        help="Generate validator from an existing instructions markdown file and skip Confluence fetch",
    )
    parser.add_argument(
        "--source-url",
        default="",
        help="Optional source URL override when using --from-instructions-file",
    )
    args = parser.parse_args()

    if args.from_instructions_file:
        source_file = Path(args.from_instructions_file)
        if not source_file.exists():
            raise RuntimeError(f"Instructions file not found: {source_file}")

        markdown_content = source_file.read_text(encoding="utf-8")
        last_updated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        source_url = args.source_url or "local.instructions"
        validator_file = write_validator_file(
            source_url=source_url,
            synced_at=last_updated,
            page_title="Development Standards",
            markdown_content=markdown_content,
        )
        print(f"Validator generated from local instructions: {validator_file!s}")
        return

    domain = require_env("CONFLUENCE_DOMAIN")
    page_id = require_env("PAGE_ID")
    email = require_env("CONFLUENCE_EMAIL")
    api_token = require_env("CONFLUENCE_API_TOKEN")

    headers = {"Accept": "application/json"}
    auth = (email, api_token)

    # Probe identity endpoint first to verify credentials are valid.
    me_url = f"https://{domain}/wiki/rest/api/user/current"
    me_response = requests.get(me_url, auth=auth, headers=headers, timeout=30)
    print(f"Identity check: {me_url} -> HTTP {me_response.status_code}")
    if me_response.status_code >= 400:
        snippet = me_response.text[:500].replace("\n", " ")
        raise RuntimeError(
            "Confluence identity check failed with "
            f"HTTP {me_response.status_code}. Response snippet: {snippet}"
        )

    # Try v2 first; fallback to v1 content API for legacy IDs.
    v2_url = f"https://{domain}/wiki/api/v2/pages/{page_id}?body-format=storage"
    response = requests.get(v2_url, auth=auth, headers=headers, timeout=30)
    print(f"Fetch attempt (v2): {v2_url} -> HTTP {response.status_code}")

    if response.status_code == 404:
        v1_url = f"https://{domain}/wiki/rest/api/content/{page_id}?expand=body.storage"
        response = requests.get(v1_url, auth=auth, headers=headers, timeout=30)
        print(f"Fetch attempt (v1 fallback): {v1_url} -> HTTP {response.status_code}")

    if response.status_code >= 400:
        snippet = response.text[:800].replace("\n", " ")
        raise RuntimeError(
            "Confluence page fetch failed with "
            f"HTTP {response.status_code}. URL: {response.url}. "
            f"Response snippet: {snippet}"
        )

    data = response.json()
    page_title = data["title"]
    html_content = data["body"]["storage"]["value"]
    webui_path = data.get("_links", {}).get("webui", "")
    if webui_path:
        page_url = f"https://{domain}{webui_path}"
    else:
        page_url = f"https://{domain}/wiki/pages/{page_id}"

    markdown_content = md(html_content, heading_style="ATX")

    last_updated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    final_content = "\n".join(
        [
            "---",
            'applyTo: "**"',
            "---",
            f"<!-- AUTO-GENERATED FROM CONFLUENCE — DO NOT EDIT MANUALLY -->",
            f"<!-- Source: {page_url} | Last synced: {last_updated} -->",
            "",
            f"# {page_title}",
            "",
            markdown_content,
            "",
        ]
    )

    output_file = Path(".github/instructions/development-standards.instructions.md")
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(final_content, encoding="utf-8")

    validator_file = write_validator_file(
        source_url=page_url,
        synced_at=last_updated,
        page_title=page_title,
        markdown_content=markdown_content,
    )

    print(f"Successfully fetched and converted: {page_title}")
    print(f"Written to: {output_file!s}")
    print(f"Validator generated: {validator_file!s}")


if __name__ == "__main__":
    main()
